name = "worker-name"
main = "index.js"
account_id = "300e650a5989b0fa689325dfe4979336"
workers_dev = true
compatibility_date = "2024-07-24"

[[routes]]
pattern = "subdomain"
custom_domain = true

[build]
command = "npm install"
