# wrangler.toml

name = "telegram-bot-worker"
compatibility_date = "2025-10-05"
main = "index.js"

# KV Namespace untuk OTP
[[kv_namespaces]]
binding = "KV_OTP"
id = "YOUR_KV_OTP_NAMESPACE_ID"  # Ganti dengan ID dari Cloudflare Dashboard

# Environment variables untuk production
[vars]
# Secrets diatur via `wrangler secret put`
[[env.production.vars]]
TELEGRAM_BOT_TOKEN = "${TELEGRAM_BOT_TOKEN}"
ADMIN_API_KEY = "${ADMIN_API_KEY}"
UPSTASH_REDIS_REST_URL = "${UPSTASH_REDIS_REST_URL}"
UPSTASH_REDIS_REST_TOKEN = "${UPSTASH_REDIS_REST_TOKEN}"

[env.production]
# route = "example.com/*" # Uncomment jika pakai custom domain

[build]
command = "npm install"
