name: Deploy to Cloudflare Workers

on:
  workflow_dispatch: # Enables manual trigger via GitHub UI or API

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: Install Wrangler
        run: npm install -g @cloudflare/wrangler
      - name: Build
        run: cargo build --release --target wasm32-unknown-unknown
      - name: Publish
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: wrangler publish
